language: python
python:
- '2.7'
sudo: required
services:
- docker
install:
- docker pull kbase/kb-sdk
- docker run kbase/kb-sdk genscript > $HOME/bin/kb-sdk
- chmod 755 $HOME/bin/kb-sdk
- export PATH=$PATH:$HOME/bin/kb-sdk
- kb-sdk sdkbase
- kb-sdk test || true
- make build-test-script
- sed -i "s/test_token=/test_token=$TEST_TOKEN/" test_local/test.cfg
- sed -i 's/$(id -u)/0:0/' test_local/run_tests.sh
script:
- kb-sdk test
env:
  global:
    secure: DSrU/SnAmvNcee058p7r8ZEeyUHa8W8mvag/zaFDb6NSDVP23g794Rb0tCwgS5kNSN73oOk+7MXNKJzoI7ydO+d1aCLyd/0wazE35t+W5iA2vDdQEsZtE5gp4TFvP88NxqVBi5qZQJ9DvQtOYLtHf7eYWj/jg8w5JmiiUYZOPkX6+p08evZFjpBE7OIavOfPTxf9b+sHJWJR2V5l2y2f468bad7FpIARYWfcNoVv6BrE2HU7WnFzjvJydEHJjq6RbNfvbAmR3gvky9jx3jC9oXJhgWHDXrPiihaoCuAreFUYTa/gOxzToD7IxCN7zl3MRZT5PHpWTq6yumyoL9SSBHrEK2J+xzqq+vJzqjBqnI/vSxehFMA91sydh1K3Ts2TDFJxijLOVQ+DCToTK1EDIKh3wh5WAMeCBLpSv3SEYjSRHU2hX7yWsgMn7CSWhxwGOTM5WLiqYbCzL9AuGTUbGL9s3MwfEw+txY1zpKWDBAEf3t7TbYuMvkL3o4fhtWmtDsdWFb9XENcdbsfHKin0GpnddlxaTJQDrTlbDzYoSCsKlpF6sY51ExCycRmqG9lU5bH+S5ayFFQaay+EI1nuXomTzaH/p7klVN3Ja6cYfO2TKw6RTlxMw1Q3Ro0NKDYc0btVTNT7j+qK5UorUfbhVBxv4DrawTjzgevhRj4ugLE=
